In [92]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 6)

In [93]:
df = pd.read_csv('Food_all.csv')
df

,Food Category,Food name,Weight,Measure,Protein,Carbohydrate,Total Fat,Protei,Magnesium,Folate,...,Lycopene,Trans fats,Vitamin E,Niacin,Phosphorus,Vitamin A,Dietary Folate Equivalents,Folate,Saturated Fat,Caffeine
0,SOUPS,"Beef or chicken, broth/bouillon",254,250mL,3,tr,1,NaN,5,5,...,NaN,NaN,NaN,NaN,33,0,NaN,NaN,0.3,NaN
1,SOUPS,"Beef, chunky",254,250mL,12,21,5,NaN,5,15,...,NaN,NaN,NaN,NaN,127,137,NaN,NaN,2.7,NaN
2,SOUPS,"Chicken noodle, chunky",254,250mL,13,18,6,NaN,10,65,...,NaN,NaN,NaN,NaN,76,71,NaN,NaN,1.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,SNACKS,"Soybeans, roasted, salted",44,60mL,15,15,11,NaN,63,NaN,...,NaN,NaN,NaN,NaN,158,4,NaN,NaN,1.6,NaN
1159,SNACKS,"Trail mix, regular",38,60mL,5,17,11,NaN,60,NaN,...,NaN,NaN,NaN,NaN,131,tr,NaN,NaN,2.1,NaN
1160,SNACKS,"Trail mix, tropical",36,60mL,2,23,6,NaN,34,NaN,...,NaN,NaN,NaN,NaN,66,1,NaN,NaN,3.0,NaN

In [94]:
general_food_categories = pd.read_csv('raw_data/Dataset_Food_Groups.csv', header=1)
general_food_categories['Food Category'] = 'GENERAL FOOD CATEGORY'
# Create a new column 'Food name' by combining 'Food Name' and 'Food Name (Alternatives)'
general_food_categories['Food name'] = (
    general_food_categories['Food Name'] + 
    ' (' + general_food_categories['Food Name (Alternatives)'].fillna('') + ')'
)
general_food_categories

,Food Name,Food Name (Alternatives),Avg Energy (kcal),Avg Protein (g),Avg Fat (g),Avg Carbohydrate (g),Avg Fibre (g),Avg Total Sugar (g),Avg Saturated Fat (g),Avg Cholesterol (mg),...,Avg Lycopene (mcg),Avg Monounsaturated Fat (g),Avg Polyunsaturated Fat (g),Avg Trans Fat (g),Avg Alcohol (g),Avg Caffeine (mg),Avg DHA (g),Avg EPA (g),Food Category,Food name
0,Meat,"Red meat, beef, pork, lamb",220,26.0,15.5,0.0,0.0,0.0,8.4,75,...,0,8.8,1.6,0.96,0.0,0,0.05,0.03,GENERAL FOOD CATEGORY,"Meat (Red meat, beef, pork, lamb)"
1,Poultry,"Chicken, turkey, duck, fowl",165,28.0,7.5,0.0,0.0,0.0,2.0,80,...,0,2.7,1.7,0.10,0.0,0,0.02,0.01,GENERAL FOOD CATEGORY,"Poultry (Chicken, turkey, duck, fowl)"
2,Fish,"Whitefish, salmon, tuna, seafood",180,22.0,8.0,0.0,0.0,0.0,2.5,85,...,0,2.0,2.5,0.10,0.0,0,0.25,0.15,GENERAL FOOD CATEGORY,"Fish (Whitefish, salmon, tuna, seafood)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,Gravy,"Sauce, meat sauce, jus",120,2.0,6.0,15.0,1.0,2.5,1.8,15,...,250,3.0,1.5,0.05,0.0,0,0.00,0.00,GENERAL FOOD CATEGORY,"Gravy (Sauce, meat sauce, jus)"
53,Soup,"Broth, stew, consommÃ©",40,2.0,1.5,5.0,1.0,1.0,0.3,5,...,50,0.8,0.5,0.00,0.0,0,0.00,0.00,GENERAL FOOD CATEGORY,"Soup (Broth, stew, consommÃ©)"
54,Stew,"Casserole, braise",150,12.0,8.0,10.0,3.0,3.0,3.0,45,...,100,4.0,3.0,0.10,0.0,0,0.60,0.20,GENERAL FOOD CATEGORY,"Stew (Casserole, braise)"

In [95]:
# Drop the original columns
general_food_categories = general_food_categories.drop(['Food Name', 'Food Name (Alternatives)'], axis=1)

In [96]:
# Reference weights (in g or mL) for each of your 55 categories:
weights = [
    75,   # Meat
    75,   # Poultry
    100,  # Fish
    100,  # Seafood
    130,  # Beans (cooked)
    130,  # Lentils (cooked)
    50,   # Sausage
    50,   # Cheese
    240,  # Milk
    125,  # Yogurt
    75,   # Vegetables
    30,   # Leafy greens
    75,   # Root vegetables
    130,  # Legumes
    70,   # Mushrooms
    150,  # Fruit (medium)
    130,  # Citrus (1 medium)
    150,  # Berries (1 cup)
    40,   # Dried fruit (Â¼ cup)
    30,   # Bread (1 slice)
    140,  # Pasta (cooked)
    140,  # Noodles (cooked)
    30,   # Cereal (dry)
    28,   # Tortilla (1)
    15,   # Sauce (per tbsp)
    15,   # Dressing (per tbsp)
    17,   # Ketchup (per tbsp)
    14,   # Mayonnaise (per tbsp)
    125,  # Tofu
    100,  # Tempeh
    50,   # Eggs (1 large)
    30,   # Greens (1 cup)
    80,   # Peas (cooked)
    90,   # Corn (cooked)
    75,   # Squash (cooked)
    160,  # Melons (1 cup)
    66,   # Stone fruits (1 medium)
    150,  # Tropical fruits (1 medium)
    158,  # Rice (cooked)
    125,  # Quinoa (cooked)
    125,  # Couscous (cooked)
    125,  # Polenta (cooked)
    40,   # Oats (dry)
    15,   # Crackers (serving)
    75,   # Fries
    28,   # Chips
    35,   # Pickles
    28,   # Nuts
    66,   # Ice cream (Â½ cup)
    16,   # Cookies (1)
    75,   # Plantâ€‘based meat
    240,  # Plantâ€‘based milk
    15,   # Gravy
    240,  # Soup (1 cup)
    240,  # Stew (1 cup)
]

# Measures (no space between number and unit; "" = one piece)
measures = [
    "75g",   # Meat
    "75g",   # Poultry
    "100g",  # Fish
    "100g",  # Seafood
    "125mL", # Beans
    "125mL", # Lentils
    "50g",   # Sausage
    "50g",   # Cheese
    "240mL", # Milk
    "125g",  # Yogurt
    "75g",   # Vegetables
    "1cup",  # Leafy greens
    "75g",   # Root vegetables
    "125mL", # Legumes
    "75g",   # Mushrooms
    "1",      # Fruit (piece)
    "1",      # Citrus (piece)
    "1cup",  # Berries
    "0.25cup",  # Dried fruit
    "1",      # Bread (slice)
    "0.5cup",  # Pasta
    "0.5cup",  # Noodles
    "30g",   # Cereal
    "1",      # Tortilla
    "1tbsp", # Sauce
    "1tbsp", # Dressing
    "1tbsp", # Ketchup
    "1tbsp", # Mayonnaise
    "125g",  # Tofu
    "100g",  # Tempeh
    "1",      # Eggs
    "1cup",  # Greens
    "125mL", # Peas
    "125mL", # Corn
    "75g",   # Squash
    "1cup",  # Melons
    "1",      # Stone fruits
    "1",      # Tropical fruits
    "0.5cup",  # Rice
    "0.5cup",  # Quinoa
    "0.5cup",  # Couscous
    "0.5cup",  # Polenta
    "40g",   # Oats
    "1",      # Crackers
    "75g",   # Fries
    "28g",   # Chips
    "35g",   # Pickles
    "28g",   # Nuts
    "0.5cup",  # Ice cream
    "1",      # Cookies
    "75g",   # Plantâ€‘based meat
    "240mL", # Plantâ€‘based milk
    "1tbsp", # Gravy
    "1cup",  # Soup
    "1cup",  # Stew
]

In [97]:
assert len(weights) == len(measures) == 55, "Weights and measures must have the same length of 55."

In [98]:
general_food_categories['Weight '] = weights
general_food_categories['Measure'] = measures
general_food_categories = general_food_categories.rename(columns={
    'Avg Protein (g)': 'Protein',
    'Avg Fat (g)': 'Total Fat',
    'Avg Carbohydrate (g)': 'Carbohydrate'
})

keep_columns = [
    'Food Category', 'Food name', 'Weight ', 'Measure', 'Protein', 'Carbohydrate', 'Total Fat'
    ]
general_food_categories = general_food_categories[keep_columns]
general_food_categories

,Food Category,Food name,Weight,Measure,Protein,Carbohydrate,Total Fat
0,GENERAL FOOD CATEGORY,"Meat (Red meat, beef, pork, lamb)",75,75g,26.0,0.0,15.5
1,GENERAL FOOD CATEGORY,"Poultry (Chicken, turkey, duck, fowl)",75,75g,28.0,0.0,7.5
2,GENERAL FOOD CATEGORY,"Fish (Whitefish, salmon, tuna, seafood)",100,100g,22.0,0.0,8.0
...,...,...,...,...,...,...,...
52,GENERAL FOOD CATEGORY,"Gravy (Sauce, meat sauce, jus)",15,1tbsp,2.0,15.0,6.0
53,GENERAL FOOD CATEGORY,"Soup (Broth, stew, consommÃ©)",240,1cup,2.0,5.0,1.5
54,GENERAL FOOD CATEGORY,"Stew (Casserole, braise)",240,1cup,12.0,10.0,8.0

In [99]:
food_all = pd.concat([df, general_food_categories], ignore_index=True)
food_all

,Food Category,Food name,Weight,Measure,Protein,Carbohydrate,Total Fat,Protei,Magnesium,Folate,...,Lycopene,Trans fats,Vitamin E,Niacin,Phosphorus,Vitamin A,Dietary Folate Equivalents,Folate,Saturated Fat,Caffeine
0,SOUPS,"Beef or chicken, broth/bouillon",254,250mL,3,tr,1,NaN,5,5,...,NaN,NaN,NaN,NaN,33,0,NaN,NaN,0.3,NaN
1,SOUPS,"Beef, chunky",254,250mL,12,21,5,NaN,5,15,...,NaN,NaN,NaN,NaN,127,137,NaN,NaN,2.7,NaN
2,SOUPS,"Chicken noodle, chunky",254,250mL,13,18,6,NaN,10,65,...,NaN,NaN,NaN,NaN,76,71,NaN,NaN,1.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,GENERAL FOOD CATEGORY,"Gravy (Sauce, meat sauce, jus)",15,1tbsp,2.0,15.0,6.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1214,GENERAL FOOD CATEGORY,"Soup (Broth, stew, consommÃ©)",240,1cup,2.0,5.0,1.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1215,GENERAL FOOD CATEGORY,"Stew (Casserole, braise)",240,1cup,12.0,10.0,8.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
food_all.to_csv('Food_all+General_items.csv', index=False)